### ISSUE TITLE
Update component after some time when using fromNow

### ISSUE THREAD

**Issue by markacola** [headzoo/react-moment#1]
The component doesn't currently have a mechanism to update the time automatically when out of date, i.e.

``` js
import React  from 'react'
import Moment from 'react-moment'

export default () => (
  <Moment fromNow>{new Date()}</Moment>
)
```

outputs:

``` html
<time>a few seconds ago</time>
```

and the content will not update over time (in a minute it will still display "a few seconds ago").

Would you accept a pull request that adds support for this?

**Comment by headzoo** [comment]
Pull request was accepted. See https://github.com/headzoo/react-moment/pull/2
