### ISSUE TITLE
I can't find a way to tell the component to usea a locale. 

### ISSUE THREAD

**Issue by HERRKIN** [headzoo/react-moment#10]
I don't know of its an issue per se but I don't see it documented so I wonder what I should do to tell the component to use a locale, I want to use the spanish locale for moment.js for example.

**Comment by headzoo** [comment]
There's nothing built into react-moment for changing the locale. At least not yet. In the meantime you should be able to set the locale globally by calling `moment.locale()`. In theory that will also change the locale of the times/dates displayed by react-moment.

http://momentjs.com/docs/#/i18n/

**Comment by HERRKIN** [comment]
I tried this 
```
import moment from 'moment'
moment().locale('es')
```
nothing happens, its weird, your component won't use moment globally I think.

**Comment by headzoo** [comment]
I wonder if the problem is from using `moment().locale('es')` vs `moment.locale('es')`. Calling moment as a function using `moment()` may be returning an instance, and your locale setting only affects that instance.
