### ISSUE TITLE
Can't resolve package

### ISSUE THREAD

**Issue by jpouillard** [headzoo/react-moment#104]
Hi,
Since 1 hour, i get this message when i want to use this package : `Can't resolve 'react-moment'`

I tried everything, uninstall / reinstall, with the `"react-moment": "https://github.com/headzoo/react-moment.git",`...

What happened ?

**Comment by jpouillard** [comment]
Can you re-deploy in NPM ? Something went wrong...

**Comment by guybeaumont** [comment]
Had the same problem, as a temporary fix, I set the version to 0.9.2 specifically, remove the ^ at the version number in your package.json

**Comment by Borquaye** [comment]
As @guybeaumont said, reverting back to the previous version will get your app to build. It seems the index.js is missing from the dist folder in 0.9.3 atm

**Comment by headzoo** [comment]
Sorry about that. Fixed in v0.9.4.
