### ISSUE TITLE
Consider pooled updates

### ISSUE THREAD

**Issue by Qard** [headzoo/react-moment#11]
The current design creates a separate timer for each individual component. If the component is used many times on a single page, it can create quite a few timers. It might be better to pull the setInterval out of the component and maintain an update function list that an external interval timer iterates over.

**Comment by headzoo** [comment]
Not a bad idea. Will give it some thought.

**Comment by headzoo** [comment]
This idea has been added to the latest update.

https://github.com/headzoo/react-moment#pooled-timer
