### ISSUE TITLE
Missing a way to change the language

### ISSUE THREAD

**Issue by gilbertorconde** [headzoo/react-moment#12]
You should add a way to change the language of the time strings. Probably a prop in the static function "getDatetime" used to: datetime.locale(prop.locale) before returning.
Something like that:

```
static getDatetime(props) {
        let {
            date,
            parse,
            utc,
            unix,
            tz,
            locale
        } = props
        date = date || props.children

        let datetime = null

        if (utc) {
            datetime = moment.utc(date, parse)
        } else if (unix) {
            datetime = moment.unix(date)
        } else {
            datetime = moment(date, parse)
        }
        if (tz) {
            datetime = datetime.tz(tz)
        }
        datetime.locale(locale ? locale : (window.navigator.userLanguage || window.navigator.language))

        return datetime
    }
```

**Comment by headzoo** [comment]
Sounds like a reasonable addition. I'll give it some thought today. A setting like locale might be best set globally, and the library currently does not have a build in mechanism for setting global configuration values. Shouldn't be a problem to add though.
