### ISSUE TITLE
Dependency failure when installing react-moment with react@17.0.1

### ISSUE THREAD

**Issue by santhoshsram** [headzoo/react-moment#126]
I see the below error when I tried to install react-moment. This is inside a react.js app that I created using create-react-app. 

[eresolve-report.txt](https://github.com/headzoo/react-moment/files/5489878/eresolve-report.txt)
[2020-11-04T18_38_53_344Z-debug.log](https://github.com/headzoo/react-moment/files/5489887/2020-11-04T18_38_53_344Z-debug.log)

$ npm install --save moment react-moment
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: petdoctor@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.6.0 || ^16.0.0" from react-moment@1.0.0
npm ERR! node_modules/react-moment
npm ERR!   react-moment@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by AllAroundD** [comment]
I get the same error. I'm on Mac. I think react_moment needs to get updated.

**Comment by headzoo** [comment]
It looks like react-moment expects React ^15.6.0 || ^16.0.0 while the error shows React 17 is installed. I haven't tested against React 17 yet but will give it a try today.

**Comment by headzoo** [comment]
@AllAroundD I just published v1.1.0 which allows for React 17 if you want to give it a try. I couldn't run the usual tests because Travis-ci is in the process of migrating to a new system and their testing is acting wonky right now.

**Comment by AllAroundD** [comment]
@headzoo sorry for the delayed reply. I tried with react 17 and got the error.
➜  client git:(master) ✗ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@"*" from @testing-library/react@11.2.2
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^11.1.0" from the root project
npm ERR!   5 more (mini-create-react-context, react-redux, react-router, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.6.0 || ^16.0.0" from react-moment@1.0.0
npm ERR! node_modules/react-moment
npm ERR!   react-moment@"^1.0.0" from the root project

**Comment by headzoo** [comment]
> npm ERR! peer react@"^15.6.0 || ^16.0.0" from react-moment@1.0.0

Thanks for getting back to me. Can you try again but upgrade to react-moment@1.1.1, first which has the corrected peer dependencies.

**Comment by AllAroundD** [comment]
This is resolved. Thank you so much.
