### ISSUE TITLE
TS2786: 'Moment' cannot be used as a JSX component. Everything worked before the upgrading to 1.1.2

### ISSUE THREAD

**Issue by Anvarmirzo** [headzoo/react-moment#148]
TS2786: 'Moment' cannot be used as a JSX component.

Its instance type 'Moment' is not a valid JSX element.

The types returned by 'render()' are incompatible between these types.

Type 'React.ReactNode' is not assignable to type 'import("C:
/Users/Dior2/Anvar/custom/smarts/smarts/client/node_modules/@types/react-router/node_modules/@types/react/index")
.ReactNode'.

Type '{}' is not assignable to type 'ReactNode'.

Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props

**Comment by tylergarside** [comment]
Receiving the same error, was still on 1.1.1 though

**Comment by gerardobort** [comment]
Same here!

**Comment by ozluy** [comment]
same here :( version 1.1.1

**Comment by heyalbertdev** [comment]
Same here

**Comment by ozluy** [comment]
```
"resolutions": {
"@types/react": "17.0.43",
}
```

 - add above snippet to your package.json under `resolutions`
 - remove your `node_modules`  folder
 - run `yarn install`
 
 Solves it, discussion can be found here => https://github.com/facebook/react/issues/24304#issuecomment-1092563688

**Comment by heyalbertdev** [comment]
@ozluy  thank you

**Comment by Anvarmirzo** [comment]
https://github.com/headzoo/react-moment/issues/148#issuecomment-1094329530 thanks!
