### ISSUE TITLE
Locale attribute not change language

### ISSUE THREAD

**Issue by PhilipeGatis** [headzoo/react-moment#17]
Hi.
Im setting locale to 'pt-br' and result is.
![image](https://cloud.githubusercontent.com/assets/4982462/24461137/a391ea4e-1476-11e7-815e-e170cce248df.png)

The language not change.
This is my code....
`<Moment locale="pt-br">{project.lastModified}</Moment>`

I doing something wrong?

**Comment by elisoncampos** [comment]
+1

**Comment by eduardoborges** [comment]
+1

**Comment by kalyanijamunkar10** [comment]
+1
