### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by timmo001** [headzoo/react-moment#20]
React.PropTypes usage is now deprecated. prop-types now needs to be used as a replacement

Refer to `dist/index.js`

**Comment by sergiocruz** [comment]
I opened a pull request addressing this, hopefully the maintainers will merge it soon 😁 

It's PR #18 just in case

**Comment by a-x-** [comment]
😫

**Comment by tsmith123** [comment]
Any news on this? Could really do with this pull request being approved.

**Comment by a-x-** [comment]
I think we need new maintainer, current is not responding recent weeks

**Comment by a-x-** [comment]
I wrote to some guys at `moment` gh org.
But they was not respond me too :(

**Comment by headzoo** [comment]
Sorry for the delays. Work has been crazy! I will get the PR merged in tomorrow.
