### ISSUE TITLE
Cant find module error

### ISSUE THREAD

**Issue by ranvirgorai** [headzoo/react-moment#24]
bundle has warnings:
./~/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale

**Comment by nicolaskern** [comment]
Was it the error you got :
```
./node_modules/moment/min/moment-with-locales.js
Module not found: Can't resolve './locale' in '/app/node_modules/moment/min'
```

Thank you!

**Comment by tke578** [comment]
FWIR, if using docker, clear out old images `docker system prune`

**Comment by claide** [comment]
had the same issue using gatsbyjs

`warn Module not found: Error: Can't resolve './locale' in 'D:\Projects\development\my-app\node_modules\moment\src\lib\locale'`
