### ISSUE TITLE
Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by fedegonzal** [headzoo/react-moment#25]
Hi, I had that error after install react-moment in a react-native project. What are I doing wrong? Thanks!

**Comment by vieraleonel** [comment]
Hi, you can solve this problem by adding the missing presets
```bash
npm install --save-dev babel-preset-es2015 babel-preset-react babel-preset-stage-2
````
Then run again

```bash
react-native run-android
#or
react-native run-ios
```
