### ISSUE TITLE
Error:  Expected a component class, got [object Object].

### ISSUE THREAD

**Issue by dmr07** [headzoo/react-moment#27]
React-Native project. Trying to display `story.date_created`, such as `2017-02-24T08:00:00.000Z`

```
import Moment from 'react-moment';
...
let dateToFormat = new Date(story.date_created);
return(
...
<View>
     <Moment date={dateToFormat} />
     <Text style={styles.author}>{story.given_name.toUpperCase() + ' ' + story.family_name.toUpperCase()}</Text>
</View>
...
)
```

React: 16.0.0-alpha.12
React-Native: 0.45.0
React-Moment: 0.2.4

**Comment by visoft** [comment]
Seeing the same thing with React Native 0.45.1. Here's what I have for versions:

**"moment": "^2.18.1"**
**"moment-timezone": "^0.5.13"**
**"react": "16.0.0-alpha.12"**
**"react-moment": "^0.2.4"**
**"react-native": "0.45.1"**

**Comment by tujoworker** [comment]
@visoft and @dmr07 Use as prop with a React Native view like Text

`<Moment as={Text}>1976-04-19T12:59-0500</Moment>`

**Comment by danstepanov** [comment]
@tujoworker Still having this issue when passing Moment a prop
```
<Moment>{this.props.fundingRound.closeDate}</Moment>
```

the value of `this.props.fundingRound.closeDate` is `2017-10-31T16:00:00`
