### ISSUE TITLE
npm WARN react-moment@0.2.4 requires a peer of react@^15.0.0 but none was installed.

### ISSUE THREAD

**Issue by Shrek53** [headzoo/react-moment#29]
Above warning shows when I try to run 
npm install --save moment moment-timezone react-moment
in my react-native project. I also can not use (import) moment 
What is the problem here ? Am I doing something wrong ? 

In my package.json file 

"dependencies": {
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "react": "16.0.0-alpha.12",
    "react-moment": "^0.2.4",
    "react-native": "0.45.1",
}

**Comment by Shrek53** [comment]
@headzoo  
Without any replay how can you close an issue ??

**Comment by headzoo** [comment]
I closed the issue because it's 20 days old, and I figured you solved your problem by now. The problem sounds like an issue with npm rather than react-moment. Have you tried the latest version of react-moment? We're up to version 0.4.2.

**Comment by aliyahcottle** [comment]
Problem still persists at version 0.6.0

**Comment by headzoo** [comment]
@aliyahcottle Which version of React are you installing? I think @Shrek53 is having a problem with using React 16.0.0-alpha.12, because react-moment requires ^15.0.0. Which means any 15.x.x version will work, but not 16.x.x.

**Comment by aliyahcottle** [comment]
Ok, ya was using 16.0.0-alpha.12 as well

**Comment by Shrek53** [comment]
It's an npm or react-native issue .
Not a react-moment issue.

**Comment by headzoo** [comment]
@Shrek53 It's all good. The ^ matches major version numbers. So "^15.0.0" matches any 15.x.x but not 14.x.x or 16.x.x.

Another thing you can try is forking the react-moment repo, and changing the package.json to require react ^16.0.0, and then use your fork in your React Native project.
