### ISSUE TITLE
Moment.startPooledTimer and FromNow doesn't work fine

### ISSUE THREAD

**Issue by GaelGRIFFON** [headzoo/react-moment#35]
Hi all,

I get errors when I try to use Moment.startPooledTimer.

In my index.js:
`Moment.startPooledTimer(3000);`

In my component:
`<Moment fromNow>{new Date(this.props.mission.deadline).toISOString()}</Moment>`

And the error on my js console:
```
index.js:1 Uncaught TypeError: Cannot read property 'fromNow' of undefined
    at t.value (index.js:1)
    at index.js:1
    at Array.forEach (<anonymous>)
    at index.js:1
```

Any idea?

**Comment by headzoo** [comment]
Okay, this should be fixed in the latest release. Run `npm update react-moment` to get the latest.
