### ISSUE TITLE
Element are not removed from pooledElements 

### ISSUE THREAD

**Issue by GaelGRIFFON** [headzoo/react-moment#36]
When component is unmount, it is not remove from pooledElements array.

I suggest something like add (not tested):

`static removePooledElement(element) {
    const index = Moment.pooledElements.indexOf(element);
    if (index  !== -1) {
      Moment.pooledElements.splice(index, 1);
    }
  }`

and on:
`clearTimer = () => {
    if (!Moment.pooledTimer && this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
    if (Moment.pooledTimer && this.timer) {
         Moment.removePooledElement(this);
    }
  };`

**Comment by headzoo** [comment]
Thanks, your changes have been applied to the latest version.
