### ISSUE TITLE
Would be nice to see react 16 support

### ISSUE THREAD

**Issue by macnibblet** [headzoo/react-moment#40]

**Comment by x7bit** [comment]
Modify the _/node_modules/react-moment/package.json_, and in section "_peerDependencies_" change this line:
`"react": "^15.0.0"`
to:
`"react": "^15.0.0 || ^16.0.0"`

Then run "_npm install --save_".

**Comment by IgorDmitriev** [comment]
@headzoo Any plans to upgrade this package for react 16 support in near future?

**Comment by headzoo** [comment]
@x7bit @IgorDmitriev All fixed in react-moment v0.6.6.
