### ISSUE TITLE
Support for local property

### ISSUE THREAD

**Issue by dmcgeown-deveire** [headzoo/react-moment#42]
Hi, this component does not seem to have support for the standard moment is "local" property. Is there a way to achieve the following using your component?

var now = moment.utc('2017-10-06T17:27:57').local().
format();

**Comment by wildsurfer** [comment]
did you find the solution? I have the same question

**Comment by Priyank57** [comment]
Same question any solution ?

**Comment by pesimeao** [comment]
Did you found a solution?

**Comment by jakemayfield** [comment]
I'm also seeking a solution for this. Thanks!

**Comment by pesimeao** [comment]
> I'm also seeking a solution for this. Thanks!

I've added this feature in this PR: https://github.com/headzoo/react-moment/pull/85

**Comment by headzoo** [comment]
Sorry about the delay. I'll look over the PR and merge it in the morning.

**Comment by jakemayfield** [comment]
@headzoo Excellent, thanks!

@pesimeao  Thanks for the PR!

I went with the plain Typescript approach for some immediate relief but I look forward to re-implementing the <Moment /> component for ease of use and consistency.
