### ISSUE TITLE
globalLocale doesn't change the language

### ISSUE THREAD

**Issue by francisrod01** [headzoo/react-moment#44]
Why `Moment.globalLocale` from `react-moment` doesn't change the locale and translate the language?

![image](https://user-images.githubusercontent.com/4691768/32603433-e4ad8fea-c530-11e7-91a8-2f4c5d38f4d3.png)

I fixed this just with `moment` but not with `react-moment`

```js
import React, {Component} from 'react'
// import Moment from "react-moment"
// import moment from "moment"
import moment from 'moment/min/moment-with-locales'
import {Text, View} from "react-native"

export default class ParseDate extends Component {
    constructor(props) {
        super(props)

        // Set the locale for every moment instance to Portuguese.
        moment.locale('pt-br')
        this.localMoment = moment()
    }

    render() {
        return (
            <View>
                {/*<Moment element={Text} format={`LLL`}>{new Date().toString()}</Moment>*/}
                <Text>{this.localMoment.format('LLLL')}</Text>
            </View>
        )
    }
}
```

output: `Quinta-feira, 9 de novembro de 2017 às 02:07`

![image](https://user-images.githubusercontent.com/4691768/32603449-ef4fc56c-c530-11e7-867e-53ffcdaf3ac3.png)

What's going on with `react-moment` locale?

References: #10 #17 #41 
https://github.com/headzoo/react-moment#global-config
https://github.com/headzoo/react-moment#usage-with-react-native

**Comment by headzoo** [comment]
It sounds like you need to explicitly import the locale. Like this:

```jsx
import React from 'react';
import Moment from 'react-moment';
import 'moment/locale/fr';

Moment.globalLocale = 'fr';

const Component = () => (
    <Moment format={`LLL`}>
        {new Date().toString()}
    </Moment>
);
```

**Comment by francisrod01** [comment]
Thank for your answer @headzoo but I need to be more "dynamic" with this right?
I think that `moment-with-locales` should solve this but it didn't work.

**Comment by headzoo** [comment]
Alright, I'm not sure what the problem is, but I have a work around. I added the `Moment.globalMoment` property to react-moment v0.6.8. Which you can use like this:

```jsx
import React, {Component} from 'react';
import {Text, View} from 'react-native';
import Moment from 'react-moment';
import moment from 'moment/min/moment-with-locales';

// Use the 'moment' instance from 'moment/min/moment-with-locales' instead of the
// default instance. Set the language to Portuguese.
Moment.globalMoment = moment;
moment.locale('pt-br');

export default class ParseDate extends Component {
    render() {
        return (
            <View>
                <Moment element={Text} format={`LLL`}>{new Date().toString()}</Moment>*
            </View>
        )
    }
}
```

**Comment by francisrod01** [comment]
It works on ReactJS. I'll testing to RN tomorrow.
