### ISSUE TITLE
Format to Uppercase

### ISSUE THREAD

**Issue by jaschaio** [headzoo/react-moment#45]
Hey there,
is it possible to manipulate the output after it has been parsed by moment? I am using react-moment with react-native and would like to display the date in Uppercase. Unfortunately I can't use CSS for it but have to use JavaScript `.toUpperCase()` method.

Couldn't find a way to manipulate the output beside the Format Parameter which doesn't help in this case.

**Comment by jaschaio** [comment]
By the way in the original moment library it's possible to [customize a local](http://momentjs.com/docs/#/customization/). This would work for me as well, but the original moment object is not exposed through the wrapper and there is no `customizeLocale` prop.

**Comment by headzoo** [comment]
I added the `filter` and `Moment.globalFilter` props to v0.6.7.

https://github.com/headzoo/react-moment#filter

**Comment by jaschaio** [comment]
Are you kidding me? That was fast! Thanks :)

**Comment by headzoo** [comment]
You had a good idea. Thanks for the input!
