### ISSUE TITLE
moment().from() / moment.to() Boolean parameter

### ISSUE THREAD

**Issue by danielparas** [headzoo/react-moment#48]
Hey, first of all thanks for this great package! :)

I can't seem to figure out how to pass the optional Boolean parameter to the from and to properties, which allows for disabling the "in" or "ago" text and just gives the time from/to eg. "5 Years" vs "5 Years ago".

example from moment's documentation `end.from(start, true); // "5 days"`

Is this possible after all?

Thanks
Daniel

**Comment by mchudy** [comment]
I also had a hard time figuring this out - turns out there is already a parameter for that. It's called `ago` - the name is somewhat counterintuitive and it's only mentioned in documentation for `fromNow` (`from`, `to` and `toNow` use it in the same way).

**Comment by danielparas** [comment]
Awesome - worked! thanks for this @mchudy 

Yes it's strange indeed. thanks again 👍
