### ISSUE TITLE
Invariant Violation "view config not found for name time"

### ISSUE THREAD

**Issue by psn80** [headzoo/react-moment#53]
```
import Moment from 'react-moment';
....
<Text style={styles.date} >  <Moment> {data.last_login}</Moment> </Text>
```
data.last_login = "2017-11-20T17:57:14.000Z"
Code is working without Moment

**Comment by abdalafer** [comment]
Same issue here. Were you able to resolve it @psn80 ?

**Comment by shelker** [comment]
Are you using Moment in React Native @abdalafer ?

Just integrate element={Text}
see https://www.npmjs.com/package/react-moment#usage-with-react-native

**Comment by headzoo** [comment]
Thanks @shelker. I assume this fixes their issue.
