### ISSUE TITLE
How to use react-moment with millisecods

### ISSUE THREAD

**Issue by husnaingoldev** [headzoo/react-moment#57]
Thanks guys for such a great module.

I need to ask, how can i use react-moment with milliseconds instead of timestamps.
for example when i use
`<Moment interval={20000} fromNow element={Text} unix>1517895695215</Moment>`

i get **in 48052 years**., instead it should return **7hours** (as of writing this question)

**Comment by husnaingoldev** [comment]
I got the solution by doing `1517895695215/1000`, now i am getting desired results.
Thanks guys.

**Comment by knapcio** [comment]
I've checked the code and figured out using 'utc' instead of 'unix' param works fine with milliseconds.
