### ISSUE TITLE
typings: Missing dependency react-native

### ISSUE THREAD

**Issue by fuglu** [headzoo/react-moment#70]
The [index.d.ts](https://github.com/headzoo/react-moment/blob/master/dist/index.d.ts#L2) file references the `react-native` module but this module is not listed as a dependency.

Maybe we could use
```js
import { CSSProperties } from "react";
// ...
style?: CSSProperties,
```
instead of
```js
import { ViewStyle } from 'react-native';
// ...
style?: ViewStyle,
```
since `react` is already listed as a dependency?

**Comment by headzoo** [comment]
Alright, changes published in v0.7.9. Hopefully that works.
