### ISSUE TITLE
Global Calendar config

### ISSUE THREAD

**Issue by bgold0** [headzoo/react-moment#72]
Is there a way to update a global calendar config like in the [MomentJS example here](
https://momentjs.com/docs/#/customization/calendar/)?

I saw the [global config option](https://github.com/headzoo/react-moment#global-config) in the read me but didn't see anything about the calendar.

**Comment by headzoo** [comment]
You should be able to use `globalMoment` which is the moment instance used internally by the library. Something like this in your index.js before using `<Moment />` anywhere:

```jsx
import Moment from 'react-moment';

Moment.globalMoment.updateLocale('en', {
    calendar : Object
});
```

**Comment by bgold0** [comment]
So wierd, I thought it was working but now I get some random error:

```
Cannot read property 'updateLocale' of null
TypeError: Cannot read property 'updateLocale' of null
```

**Comment by headzoo** [comment]
Okay, I see what I did wrong. Give this a try.

```jsx
import moment from 'moment';
import Moment from 'react-moment';

moment.updateLocale('en', {
    calendar : Object
});
Moment.globalMoment = moment;
```

**Comment by bgold0** [comment]
Looks like that did the trick (for now haha). Thank you!

**Comment by bgold0** [comment]
@oxyii this is for the calendar `<Moment calendar={true} />`

**Comment by oxyii** [comment]
Thanks for your reply. I changed config from calendar to fromNow. Still not working. In pure moment also not working. I think `fromNow` don't use `lastDay` key. My question is not for you. I will deal with pure moment.js )))) Thanks
