### ISSUE TITLE
Examples aren't working

### ISSUE THREAD

**Issue by BattulgaTS** [headzoo/react-moment#80]
I'm getting this error with this example code from Readme.md

```
render() {
  const dateToFormat = '1976-04-19T12:59-0500';
  return (
    <div>
      <Moment>{dateToFormat}</Moment>
    </div>
  )
}
```

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by uSkizzik** [comment]
@theTulga I'm having the same issue, I doubt you have any info 4 years later but it's still worth the shot. What fixed it?
