### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by berndverhofstadt** [headzoo/react-moment#84]
Hi, I'm currently using `"react": "16.3.2"` and it seems that this version is not compatible with react-moment.

Error that I get:
``` bash
error TS2605: JSX element type 'Moment' is not a constructor function for JSX elements.
[tsc] Types of property 'render' are incompatible.
[tsc] Type '() => ReactNode' is not assignable to type '{ (): ReactNode; (): ReactNode; (): false | Element; }'.
[tsc] Type 'ReactNode' is not assignable to type 'false | Element'.
[tsc] Type 'string' is not assignable to type 'false | Element'.
```

Cheers, Bernd

**Comment by 0x111** [comment]
Could you provide an example of your usage? I have just tried the library today and I am using `"react": "^16.6.0",`  and the basic example works without an issue, so it may be something else in your case that is causing trouble.

**Comment by berndverhofstadt** [comment]
If I use moment it works fine, probably a dependency, I'll close this issue.
