### ISSUE TITLE
If number of days > 25, fromNow evaluates to a month ago.

### ISSUE THREAD

**Issue by saurabhpati** [headzoo/react-moment#86]
My use case:

If the difference of date from now is more than a month I want to display the original date in 'YYYY/MM/DD' format else I wish to see the difference using the ```fromNow``` option.

So I have the following logic:

```
export function getLastModifiedDate(updateDateString: string): React.ReactNode {
    const today = new Date();
    const date = new Date(updateDateString);
    const millisecondDiff = (today as any) - (date as any);
    const dayDiff = millisecondDiff / DateConstants.MillisecondsInADay;

   // #TODO: Improve this logic to accomodate months of 31 days
    if (dayDiff <= 30 ) {
        return <Moment fromNow>{date.toString()}</Moment>;
    }

    return <Moment format="YYYY/MM/DD">{date.toString()}</Moment>;
}
```

But if ```dayDiff``` > 25, it renders 'a month ago'.

Screenshot while debugging: 26 is the day difference
![image](https://user-images.githubusercontent.com/20544414/52552969-147f1680-2e08-11e9-9dca-92948899acdf.png)

Here is what it renders:
![image](https://user-images.githubusercontent.com/20544414/52553032-4c865980-2e08-11e9-8ac3-0092199f6924.png)

I have tried to read the docs and try other things like durationFromNow, diff and other stuff as well but I am stuck. 

Can anybody help me on this?

**Comment by encbladexp** [comment]
Just take a look at the [Documentation](https://momentjs.com/docs/#/customization/relative-time-threshold/)

**Comment by saurabhpati** [comment]
Thanks
