### ISSUE TITLE
Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by MalinPramoditha** [headzoo/react-moment#98]
I just pasted your sample code in my react native project and this issue showed up

my code 
`            <Moment toNow>
                1976-04-19T12:59-0500
              </Moment>`
error
`Text strings must be rendered within a <Text> component.`

**Comment by jnam90** [comment]
hey bro, 

Let's do it
https://github.com/headzoo/react-moment#usage-with-react-native

```
import Moment from 'react-moment';
import { Text } from 'react-native';
```

```
<Moment element={Text} >1976-04-19T12:59-0500</Moment>
```
